(() => {
  'use strict';

  const $ = (s) => document.querySelector(s);
  const $$ = (s) => Array.from(document.querySelectorAll(s));
  const STATE_KEY = 'bvai.state.v4';
  const OLD_STATE_KEYS = ['bvai.state.v2'];
  const PROFILE_KEY = 'bvai.player.profile.v1';
  const GRAVITY = 1450;

  const profileDefaults = { gender: 'girl', name: 'Laura', number: 10 };
  const stateDefaults = {
    level: 1, xp: 0, money: 150, fans: 0,
    bestScore: 0, bestCombo: 0, perfectShots: 0, rimHits: 0, bankShots: 0,
    wins: 0, losses: 0, draws: 0,
    totalMade: 0, leaderboard: [],
    upgrades: { stability: 0, focus: 0, power: 0, bank: 0, clutch: 0 },
    skins: { ball: 'classic', court: 'arena', board: 'pro', trail: 'gold' },
    ownedSkins: { ball: ['classic'], court: ['arena'], board: ['pro'], trail: ['gold'] },
    daily: { date: '', missions: [] },
    league: { standings: [] },
    tutorialDone: false,
    modeStats: {}
  };

  const AI = {
    rookie: { name: 'Rookie Bot', accuracy: 0.42, interval: 2.6, badge: 'Easy', mode: 'classic' },
    sniper: { name: 'Sniper AI', accuracy: 0.68, interval: 2.2, badge: 'Perfect', perfectBonus: true },
    bank: { name: 'Bank King', accuracy: 0.63, interval: 2.35, badge: 'Bank', bankBonus: true },
    chaos: { name: 'Chaos Bot', accuracy: 0.64, interval: 2.1, badge: 'Wind', windBonus: true },
    legend: { name: 'Legend AI', accuracy: 0.82, interval: 1.75, badge: 'Boss', boss: true }
  };
  const AI_ORDER = ['rookie', 'sniper', 'bank', 'chaos', 'legend'];

  const UPGRADES = [
    { id: 'stability', name: 'Stabilitate', desc: 'Zona perfectă devine mai mare.', base: 120, max: 5 },
    { id: 'focus', name: 'Focus', desc: 'Vântul afectează mai puțin mingea.', base: 140, max: 5 },
    { id: 'power', name: 'Power Control', desc: 'Bara de putere se mișcă mai lent.', base: 150, max: 5 },
    { id: 'bank', name: 'Bank Master', desc: 'Bonus mai mare la panou.', base: 180, max: 4 },
    { id: 'clutch', name: 'Clutch', desc: 'Ultimele 10 secunde dau scor dublu.', base: 220, max: 3 }
  ];
  const SKINS = {
    ball: [{ id:'classic', name:'Clasică', cost:0 }, { id:'neon', name:'Neon', cost:220 }, { id:'fire', name:'Foc', cost:360 }, { id:'ice', name:'Gheață', cost:360 }, { id:'gold', name:'Aurie', cost:520 }],
    court: [{ id:'arena', name:'Sală', cost:0 }, { id:'street', name:'Stradă', cost:260 }, { id:'night', name:'Noapte', cost:320 }, { id:'beach', name:'Plajă', cost:420 }],
    board: [{ id:'pro', name:'Pro', cost:0 }, { id:'cyber', name:'Cyber', cost:300 }, { id:'retro', name:'Retro', cost:280 }],
    trail: [{ id:'gold', name:'Gold', cost:0 }, { id:'neon', name:'Neon', cost:240 }, { id:'fire', name:'Fire', cost:300 }, { id:'ice', name:'Ice', cost:300 }]
  };
  const MODE_LABELS = { classic:'Clasic', blitz:'Blitz', moving:'Coș mobil', wind:'Vânt haotic', bank:'Bank lab', sudden:'Sudden Death', perfect:'Only Perfect', comeback:'Comeback', mirror:'Mirror AI', bossrush:'Boss Rush' };
  const DIFF_LABELS = { easy:'Ușor', normal:'Normal', hard:'Greu', pro:'Pro' };

  let state = readState();
  let profile = readJson(PROFILE_KEY, profileDefaults);
  let lang = localStorage.getItem('bvai.lang') || 'ro';
  let soundOn = true;
  let audioCtx = null;
  let raf = 0;

  const game = { canvas:null, ctx:null, w:900, h:540, running:false, last:0, match:null, trails:[], particles:[], slowMo:0 };

  function readJson(key, fallback) { try { return merge(fallback, JSON.parse(localStorage.getItem(key)) || {}); } catch { return structuredClone(fallback); } }
  function merge(a,b){ const out = Array.isArray(a) ? [...a] : { ...a }; for (const [k,v] of Object.entries(b||{})) out[k] = v && typeof v === 'object' && !Array.isArray(v) && a[k] ? merge(a[k], v) : v; return out; }
  function readState(){ let current = readJson(STATE_KEY, stateDefaults); if (!localStorage.getItem(STATE_KEY)) for (const k of OLD_STATE_KEYS) { const old = localStorage.getItem(k); if (old) { try { current = merge(current, JSON.parse(old)); break; } catch {} } } return current; }
  function saveState(){ try { localStorage.setItem(STATE_KEY, JSON.stringify(state)); } catch {} }
  function saveProfile(){ profile.name = String(profile.name || 'Player').trim().slice(0,14) || 'Player'; profile.number = Math.max(0, Math.min(99, parseInt(profile.number,10)||0)); profile.gender = profile.gender === 'boy' ? 'boy' : 'girl'; try { localStorage.setItem(PROFILE_KEY, JSON.stringify(profile)); } catch {} }
  function xpNeed(){ return Math.round(100 * Math.pow(1.35, state.level - 1)); }
  function fmt(n){ return Number(n||0).toLocaleString(lang === 'ro' ? 'ro-RO' : 'en-US'); }
  function text(sel,val){ const el=$(sel); if(el) el.textContent=val; }
  function upgrade(id){ return state.upgrades?.[id] || 0; }
  function upgradeCost(item){ return Math.round(item.base * Math.pow(1.55, upgrade(item.id))); }

  function tone(type='click'){
    if(!soundOn) return;
    try{ audioCtx ||= new (window.AudioContext || window.webkitAudioContext)(); const osc=audioCtx.createOscillator(), gain=audioCtx.createGain(); const f={click:420,score:880,rim:220,miss:140,win:720,perfect:1320,combo:980}[type]||420; const now=audioCtx.currentTime; osc.type=type==='rim'?'square':'sine'; osc.frequency.setValueAtTime(f,now); gain.gain.setValueAtTime(type==='perfect'?.09:.055,now); gain.gain.exponentialRampToValueAtTime(.0001,now+.16); osc.connect(gain).connect(audioCtx.destination); osc.start(now); osc.stop(now+.18); }catch{}
  }
  function toast(msg,kind=''){ const el=$('#toast'); if(!el)return; el.textContent=msg; el.className=`toast ${kind}`.trim(); el.hidden=false; requestAnimationFrame(()=>el.classList.add('show')); clearTimeout(toast.t); toast.t=setTimeout(()=>{el.classList.remove('show'); setTimeout(()=>{el.hidden=true},260)},1600); }
  function comboFlash(msg){ let el=$('#combo-flash'); if(!el){ el=document.createElement('div'); el.id='combo-flash'; el.className='combo-flash'; $('.court-wrap')?.appendChild(el); } el.textContent=msg; el.classList.remove('show'); void el.offsetWidth; el.classList.add('show'); tone('combo'); }
  function slowMo(){ const wrap=$('.court-wrap'); if(!wrap)return; wrap.classList.add('slowmo'); setTimeout(()=>wrap.classList.remove('slowmo'),550); }

  function todayKey(){ const d=new Date(); return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`; }
  function ensureDaily(){ if(state.daily.date===todayKey() && state.daily.missions?.length) return; state.daily={date:todayKey(),missions:[{id:'bank3',name:'Marchează 3 bank shots',type:'bank',target:3,progress:0,reward:90,done:false},{id:'hard1',name:'Câștigă un meci pe Greu',type:'hardWin',target:1,progress:0,reward:120,done:false},{id:'combo5',name:'Fă combo x5',type:'combo',target:5,progress:0,reward:110,done:false},{id:'diff10',name:'Bate AI-ul la 10 puncte diferență',type:'diff10',target:1,progress:0,reward:160,done:false}]}; saveState(); }
  function progressMission(type,value=1){ ensureDaily(); for(const m of state.daily.missions){ if(m.done||m.type!==type) continue; if(type==='combo') m.progress=Math.max(m.progress,value); else m.progress+=value; if(m.progress>=m.target){ m.done=true; state.money+=m.reward; state.xp+=Math.round(m.reward/2); toast(`Misiune completă: ${m.name} +${m.reward}$`,'gold'); } } saveState(); }

  function ensureLeague(){ if(state.league?.standings?.length) return; state.league={standings:[{name:`⭐ ${profile.name}`,pts:0,you:true},{name:'Rookie Bot',pts:11},{name:'Sniper AI',pts:9},{name:'Bank King',pts:8},{name:'Chaos Bot',pts:7},{name:'Legend AI',pts:5}]}; }
  function syncLeagueName(){ ensureLeague(); const you=state.league.standings.find(x=>x.you); if(you) you.name=`⭐ ${profile.name||'Tu'}`; }

  function injectModeOptions(){ const field = document.querySelector('fieldset'); if(!field || field.dataset.v4Modes) return; field.dataset.v4Modes='1'; [['sudden','Sudden Death'],['perfect','Only Perfect'],['comeback','Comeback'],['mirror','Mirror AI'],['bossrush','Boss Rush']].forEach(([v,label])=>{ const l=document.createElement('label'); l.innerHTML=`<input type="radio" name="mode" value="${v}"><span>${label}</span>`; field.appendChild(l); }); }

  function injectProfileUi(){ if($('#player-profile-card')) return; const panel=$('.tab-panel[data-panel="career"]'); if(!panel)return; const card=document.createElement('section'); card.id='player-profile-card'; card.className='profile-card'; card.innerHTML=`<h3>Profil jucător</h3><div class="profile-grid"><label><span>Gen</span><select id="profile-gender"><option value="girl">Fată</option><option value="boy">Băiat</option></select></label><label><span>Nume</span><input id="profile-name" type="text" maxlength="14" autocomplete="off"></label><label><span>Număr tricou</span><input id="profile-number" type="number" min="0" max="99"></label></div><p class="profile-hint">Se salvează automat și apare pe tricou în joc.</p>`; panel.prepend(card); $('#profile-gender').value=profile.gender; $('#profile-name').value=profile.name; $('#profile-number').value=profile.number; const update=()=>{ profile.gender=$('#profile-gender').value; profile.name=$('#profile-name').value; profile.number=$('#profile-number').value; saveProfile(); syncLeagueName(); renderHero(); renderHub(); draw(); }; ['change','input'].forEach(ev=>card.addEventListener(ev,update)); }
  function injectSkinUi(){ if($('#skin-panel')) return; const shopPanel=$('.tab-panel[data-panel="shop"]'); if(!shopPanel)return; const panel=document.createElement('section'); panel.id='skin-panel'; panel.className='feature-panel'; panel.innerHTML=`<h3>Skin-uri</h3><div class="skin-row"><label>Minge<select id="skin-ball"></select></label><label>Teren<select id="skin-court"></select></label><label>Panou<select id="skin-board"></select></label><label>Trail<select id="skin-trail"></select></label></div>`; shopPanel.appendChild(panel); ['ball','court','board','trail'].forEach(type=>{ const sel=$(`#skin-${type}`); sel.innerHTML=SKINS[type].map(s=>`<option value="${s.id}">${s.name}${isOwned(type,s.id)?'':' · '+s.cost+'$'}</option>`).join(''); sel.value=state.skins[type]; sel.addEventListener('change',()=>{ const val=sel.value; const skin=SKINS[type].find(x=>x.id===val); if(!isOwned(type,val)){ if(state.money<skin.cost){ toast('Fonduri insuficiente','bad'); sel.value=state.skins[type]; return; } state.money-=skin.cost; state.ownedSkins[type].push(val); toast(`Skin cumpărat: ${skin.name}`,'gold'); } state.skins[type]=val; saveState(); renderHub(); draw(); }); }); }
  function isOwned(type,id){ state.ownedSkins[type] ||= []; return state.ownedSkins[type].includes(id); }

  function renderHero(){ text('#hs-level',state.level); text('#hs-xp',fmt(state.xp)); text('#hs-fans',fmt(state.fans)); text('#hs-best',fmt(state.bestScore)); }
  function renderHub(){ ensureDaily(); ensureLeague(); syncLeagueName(); injectProfileUi(); injectSkinUi(); text('#kpi-level',state.level); text('#kpi-money',fmt(state.money)); text('#kpi-fans',fmt(state.fans)); text('#kpi-best',fmt(state.bestScore)); text('#kpi-perfect',state.perfectShots); text('#kpi-rim',state.rimHits); text('#kpi-bank',state.bankShots); text('#kpi-combo',state.bestCombo); text('#xp-now',state.xp); text('#xp-need',xpNeed()); const xp=$('#xp-fill'); if(xp)xp.style.width=`${Math.min(100,state.xp/xpNeed()*100)}%`;
    const achv=$('#achv-list'); if(achv)achv.innerHTML=[['🏀','Primul coș',state.totalMade>=1],['✨','10 perfecte',state.perfectShots>=10],['🏦','Bank master',state.bankShots>=15],['🔥','Combo x5',state.bestCombo>=5]].map(a=>`<li class="${a[2]?'done':''}"><strong>${a[0]} ${a[1]}</strong><span class="pts">${a[2]?'✓':'—'}</span></li>`).join('');
    const shop=$('#shop-list'); if(shop)shop.innerHTML=UPGRADES.map(item=>{ const lvl=upgrade(item.id), max=lvl>=item.max, cost=upgradeCost(item); return `<li><div><strong>${item.name} Lv ${lvl}/${item.max}</strong><small>${item.desc}</small></div><button data-buy="${item.id}" ${max?'disabled':''}>${max?'MAX':cost+'$'}</button></li>`; }).join(''); shop?.querySelectorAll('[data-buy]').forEach(btn=>btn.onclick=()=>buyUpgrade(btn.dataset.buy));
    const daily=$('#daily-list'); if(daily)daily.innerHTML=state.daily.missions.map(m=>`<li class="${m.done?'done':''}"><div class="d-head"><strong>${m.name}</strong><em>+${m.reward}$</em></div><div class="pbar"><div class="pfill" style="width:${Math.min(100,m.progress/m.target*100)}%"></div></div><div class="pmeta">${m.progress}/${m.target}${m.done?' ✓':''}</div></li>`).join('');
    const tour=$('#tour-bracket'); if(tour)tour.innerHTML=AI_ORDER.map((id,i)=>`<div class="tour-row"><div class="name you">${i+1}. ${profile.name}</div><div class="vs">vs</div><div class="name">${AI[id].name}${AI[id].boss?'<span class="boss-badge">BOSS</span>':''}</div></div>`).join('');
    const rows=state.league.standings.slice(0,10).map(r=>`<li class="${r.you?'you':''}"><span></span><strong>${r.name}</strong><span class="pts">${r.pts}</span></li>`).join(''); const leader=$('#leader-list'),league=$('#league-list'); if(leader)leader.innerHTML=leaderboardRows()+rows; if(league)league.innerHTML=rows;
  }
  function leaderboardRows(){ return (state.leaderboard||[]).slice(0,10).map((r,i)=>`<li><span>${i+1}</span><strong>${r.score} pts · ${r.mode} <span class="ghost-chip">${r.diff}</span></strong><span class="pts">${r.date}</span></li>`).join(''); }
  function buyUpgrade(id){ const item=UPGRADES.find(x=>x.id===id); if(!item)return; const lvl=upgrade(id); if(lvl>=item.max)return; const cost=upgradeCost(item); if(state.money<cost){toast('Fonduri insuficiente','bad');return;} state.money-=cost; state.upgrades[id]=lvl+1; saveState(); renderHub(); toast(`Cumpărat: ${item.name}`,'gold'); }

  function setupCanvas(){ const cv=$('#court'); if(!cv)return false; const ctx=cv.getContext('2d'); if(!ctx)return false; game.canvas=cv; game.ctx=ctx; const resize=()=>{ const r=cv.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2); game.w=Math.max(1,r.width); game.h=Math.max(1,r.height); cv.width=Math.floor(game.w*d); cv.height=Math.floor(game.h*d); ctx.setTransform(d,0,0,d,0,0); draw(); }; resize(); window.addEventListener('resize',resize); return true; }
  function getSelectedMode(){ return $('input[name="mode"]:checked')?.value || 'classic'; }
  function getSelectedDiff(){ return $('input[name="diff"]:checked')?.value || 'normal'; }
  function chooseAI(mode,diff,tour=false){ if(tour){ const idx=Math.min(AI_ORDER.length-1,state.tourIndex||0); return AI_ORDER[idx]; } if(mode==='bossrush')return AI_ORDER[Math.min(AI_ORDER.length-1,state.bossRushIndex||0)]; if(mode==='wind')return 'chaos'; if(mode==='bank')return 'bank'; if(diff==='pro')return 'legend'; if(diff==='hard')return 'sniper'; return 'rookie'; }
  function newMatch(tour=false){ const mode=getSelectedMode(), diff=getSelectedDiff(), aiId=chooseAI(mode,diff,tour), ai=AI[aiId]; const time=Number($('input[name="time"]:checked')?.value||60); return { mode,diff,timeLeft:mode==='blitz'?30:time,you:mode==='comeback'?0:0,ai:mode==='comeback'?10:0,perfect:0,rim:0,bank:0,combo:0,bestCombo:0,made:0,shots:0,power:0,charging:false,chargeStart:0,aimAngle:Number($('#aim')?.value||0),ball:null,ended:false,aiId,aiName:ai.name,aiNext:1.8,wind:0,rimT:0,accuracy:ai.accuracy,passPlayer:1,p1:0,p2:0,passShots:0,tutorial:state.tutorialDone?null:{step:0,shots:0,bonus:false}}; }
  function startMatch(tour=false){ if(!game.ctx&&!setupCanvas())return; game.match=newMatch(tour); game.running=true; game.trails=[]; game.particles=[]; game.last=performance.now(); $('#overlay')&&( $('#overlay').hidden=true ); text('#sb-mode',MODE_LABELS[game.match.mode]||'Clasic'); text('#sb-diff',`${DIFF_LABELS[game.match.diff]||'Normal'} · ${game.match.aiName}`); cancelAnimationFrame(raf); tone('click'); raf=requestAnimationFrame(loop); updateTutorial(); }
  function endMatch(force=false){ const m=game.match; if(!m)return; game.running=false; cancelAnimationFrame(raf); if(!force){ const won=m.you>m.ai, draw=m.you===m.ai; const accuracy=m.shots?Math.round(m.made/m.shots*100):0; const xp=30+m.you*5+(won?50:draw?20:0)+(m.tutorial?.bonus?50:0), money=20+m.you*4+(won?40:0), fans=5+m.you*2+(won?30:0); state.bestScore=Math.max(state.bestScore,m.you); state.bestCombo=Math.max(state.bestCombo,m.bestCombo); state.perfectShots+=m.perfect; state.rimHits+=m.rim; state.bankShots+=m.bank; state.totalMade+=m.made; state.money+=money; state.fans+=fans; state.xp+=xp; while(state.xp>=xpNeed()){state.xp-=xpNeed();state.level++;} if(won)state.wins++; else if(draw)state.draws++; else state.losses++; if(won&&m.diff==='hard')progressMission('hardWin'); if(won&&m.you-m.ai>=10)progressMission('diff10'); state.leaderboard=[{score:m.you,mode:MODE_LABELS[m.mode]||m.mode,diff:DIFF_LABELS[m.diff]||m.diff,date:new Date().toLocaleDateString('ro-RO')},...(state.leaderboard||[])].sort((a,b)=>b.score-a.score).slice(0,10); saveState(); renderHero(); renderHub(); showAfterMatch({won,draw,accuracy,xp,money,fans,score:`${m.you}-${m.ai}`,perfect:m.perfect,bank:m.bank,combo:m.bestCombo}); tone(won?'win':'miss'); } else { text('#ov-title','Start'); text('#ov-msg','Țintește, ține apăsat pentru putere, eliberează lângă zona aurie.'); $('#overlay')&&($('#overlay').hidden=false); } game.match=null; draw(); }

  function showAfterMatch(d){ let card=$('#after-card'); if(!card){ card=document.createElement('div'); card.id='after-card'; card.className='after-card'; card.hidden=true; document.body.appendChild(card); } card.innerHTML=`<div class="after-box"><h2>${d.won?'Victorie!':d.draw?'Egal':'Înfrângere'}</h2><p>Scor final: <strong>${d.score}</strong></p><div class="after-grid"><div class="after-stat"><span>Acuratețe</span><strong>${d.accuracy}%</strong></div><div class="after-stat"><span>Perfecte</span><strong>${d.perfect}</strong></div><div class="after-stat"><span>Bank</span><strong>${d.bank}</strong></div><div class="after-stat"><span>Combo max</span><strong>${d.combo}</strong></div><div class="after-stat"><span>XP</span><strong>+${d.xp}</strong></div><div class="after-stat"><span>Bani/Fani</span><strong>+${d.money}$ · +${d.fans}</strong></div></div><div class="after-actions"><button class="btn ghost" id="after-hub">Hub</button><button class="btn primary" id="after-again">Joacă iar</button></div></div>`; card.hidden=false; $('#after-again').onclick=()=>{card.hidden=true;startMatch();}; $('#after-hub').onclick=()=>{card.hidden=true; $('#btn-hub')?.click();}; }
  function rimPosition(){ const m=game.match; let x=game.w*.78,y=game.h*.38; if(m?.mode==='moving'||(m?.mode==='bossrush'&&m.aiId==='legend')) x+=Math.sin(m.rimT)*game.w*.06; return {x,y,r:game.w*.048}; }
  function perfectRange(){ const bonus=upgrade('stability')*.025; return {min:.6-bonus,max:.72+bonus}; }
  function chargeSpeed(){ return 1 - upgrade('power')*.09; }
  function windMultiplier(){ return Math.max(.25,1-upgrade('focus')*.14); }
  function startShot(){ const m=game.match; if(!m||m.ball||m.ended)return; m.charging=true; m.chargeStart=performance.now(); m.power=0; }
  function releaseShot(){ const m=game.match; if(!m||!m.charging)return; m.charging=false; if(m.ball||m.power<.08){m.power=0;return;} const px=game.w*.18,py=game.h*.79-game.h*.22,ang=-Math.PI/2.4+(m.aimAngle*Math.PI/180),v=8+m.power*12,range=perfectRange(); m.ball={x:px,y:py,vx:Math.cos(ang)*v*60,vy:Math.sin(ang)*v*60,life:0,perfect:m.power>=range.min&&m.power<=range.max,bankAttempt:Math.abs(m.aimAngle)>18,bankHit:false,rimHit:false}; m.shots++; m.power=0; if(m.tutorial){m.tutorial.shots++; if(m.tutorial.shots>=2){state.tutorialDone=true; saveState(); m.tutorial=null; hideTutorial();}} }
  function update(dt){ const m=game.match;if(!m)return; if(m.charging){ let p=((performance.now()-m.chargeStart)/1000*chargeSpeed())%2; if(p>1)p=2-p; m.power=p; } m.timeLeft-=dt; if(m.timeLeft<=0){m.timeLeft=0;endMatch(false);return;} if(m.mode==='wind'||m.aiId==='chaos'){m.wind+=(Math.random()-.5)*120*dt;m.wind=Math.max(-90,Math.min(90,m.wind));}else m.wind=0; if(m.mode==='moving'||m.mode==='bossrush')m.rimT+=dt*1.2; aiStep(m,dt); if(m.ball)updateBall(m,m.ball,dt); updateUi(); updateTutorial(); }
  function aiStep(m,dt){ if(m.mode==='sudden'||m.mode==='perfect'){} m.aiNext-=dt; if(m.aiNext>0)return; const ai=AI[m.aiId]; m.aiNext=ai.interval+Math.random()*1.6; let acc=m.accuracy; if(ai.windBonus&&Math.abs(m.wind)>20)acc+=.12; if(Math.random()<acc){ let pts=Math.random()<.15?3:2; if(ai.perfectBonus&&Math.random()<.35)pts++; if(ai.bankBonus&&Math.random()<.45)pts++; if(ai.boss&&m.timeLeft<10)pts*=2; m.ai+=pts; } }
  function updateBall(m,b,dt){ const px=b.x,py=b.y; b.vy+=GRAVITY*dt; b.vx+=m.wind*windMultiplier()*dt; b.x+=b.vx*dt; b.y+=b.vy*dt; b.life+=dt; game.trails.push({x:b.x,y:b.y,life:.35,type:state.skins.trail}); if(game.trails.length>28)game.trails.shift(); const r=rimPosition(),br=game.w*.018,crossed=py<r.y&&b.y>=r.y,t=(r.y-py)/Math.max(.001,b.y-py),cx=px+(b.x-px)*Math.max(0,Math.min(1,t)); if((crossed&&b.vy>0&&cx>r.x-r.r+4&&cx<r.x+r.r*.45-4)||(b.vy>0&&Math.abs(b.x-r.x)<r.r&&Math.abs(b.y-r.y)<br+8)){score(m,b);return;} const boardX=r.x+r.r*1.4; if(b.x+br>=boardX&&b.vx>0&&b.y>=r.y-r.r*2.5&&b.y<=r.y-r.r*.2){b.vx=-Math.abs(b.vx)*.65;b.x=boardX-br;b.bankHit=true;tone('rim');} const rimL=r.x-r.r,rimR=r.x+r.r*.45,hit=b.vy>0&&Math.abs(b.y-r.y)<br+5&&(Math.abs(b.x-rimL)<br+2||Math.abs(b.x-rimR)<br+2); if(hit&&!b.rimHit){b.vx=(b.x<r.x?Math.abs(b.vx):-Math.abs(b.vx))*.65;b.vy=-Math.abs(b.vy)*.55;b.rimHit=true;m.rim++;tone('rim');} if((b.life>.7&&Math.abs(b.x-r.x)<120&&Math.abs(b.y-r.y)<120&&Math.hypot(b.vx,b.vy)<220)||b.y>game.h*.92||b.x<-60||b.x>game.w+60||b.life>5)miss(m); }
  function score(m,b){ let pts=2,label='SWISH!',kind='good'; if(m.mode==='perfect'&&!b.perfect){miss(m);return;} if(b.bankHit||b.bankAttempt||m.mode==='bank'){pts+=1+upgrade('bank');m.bank++;label='BANK!';kind='gold';progressMission('bank');} if(b.perfect&&!b.rimHit){pts++;m.perfect++;label='PERFECT';kind='gold';slowMo();tone('perfect'); if(m.tutorial&&!m.tutorial.bonus){m.tutorial.bonus=true;toast('Bonus tutorial: +50 XP','gold');}} if(b.rimHit)m.rim++; m.combo++;m.bestCombo=Math.max(m.bestCombo,m.combo); if(m.combo>=3)pts++; if(m.combo===3)comboFlash('ON FIRE 🔥'); if(m.combo===5)comboFlash('COMBO x5 🔥'); if(m.combo===10)comboFlash('UNSTOPPABLE x10'); if(m.timeLeft<=10&&upgrade('clutch')>0)pts*=2; m.you+=pts;m.made++;m.ball=null;progressMission('combo',m.combo);toast(`${label}${m.combo>=2?` Combo x${m.combo}`:''}`,kind);tone('score'); }
  function miss(m){ if(m.mode==='sudden') { m.combo=0; m.ball=null; endMatch(false); return; } m.combo=0;m.ball=null;toast('Ratat','bad');tone('miss'); }
  function updateUi(){ const m=game.match;if(!m)return; text('#sb-time',Math.ceil(m.timeLeft));text('#sb-you',m.you);text('#sb-ai',m.ai);text('#rb-perfect',m.perfect);text('#rb-rim',m.rim);text('#rb-bank',m.bank);text('#rb-combo',m.combo);text('#rb-speed',m.ball?Math.round(Math.hypot(m.ball.vx,m.ball.vy)/10):0); const pf=$('#power-fill');if(pf)pf.style.inset=`0 ${100-m.power*100}% 0 0`; const pp=$('#power-perfect'),r=perfectRange(); if(pp){pp.style.left=`${r.min*100}%`;pp.style.width=`${(r.max-r.min)*100}%`;} const st=$('#sb-streak');if(st)st.hidden=m.combo<2;text('#sb-streak-n',m.combo); const wind=$('#rb-wind');if(wind)wind.hidden=!(m.mode==='wind'||m.aiId==='chaos');text('#rb-wind-n',Math.round(Math.abs(m.wind||0)));text('#rb-wind-arrow',(m.wind||0)>=0?'→':'←'); }

  function updateTutorial(){ const m=game.match; if(!m||!m.tutorial){hideTutorial();return;} let card=$('#tutorial-card'); if(!card){ card=document.createElement('div'); card.id='tutorial-card'; card.className='tutorial-card'; $('.court-wrap')?.appendChild(card); const arrow=document.createElement('div'); arrow.id='tutorial-arrow'; arrow.className='tutorial-arrow'; $('.court-wrap')?.appendChild(arrow); } const range=perfectRange(), power=m.power; let msg=m.charging && power>=range.min && power<=range.max ? 'Eliberează acum!' : m.charging ? 'Ține până ajungi în zona aurie.' : 'Mută ținta, apoi ține apăsat ARUNCĂ.'; card.innerHTML=`<strong>Tutorial rapid</strong>${msg}<br><small>${2-m.tutorial.shots} aruncări ghidate rămase</small>`; const arrow=$('#tutorial-arrow'); if(arrow){ arrow.style.left=m.charging?'50%':'18%'; arrow.style.top=m.charging?'calc(100% - 115px)':'calc(100% - 180px)'; } $('#power-perfect')?.classList.add('tutorial-glow'); }
  function hideTutorial(){ $('#tutorial-card')?.remove(); $('#tutorial-arrow')?.remove(); $('#power-perfect')?.classList.remove('tutorial-glow'); }

  function draw(){ if(!game.ctx)return; const ctx=game.ctx,w=game.w,h=game.h,m=game.match; ctx.clearRect(0,0,w,h); drawBackground(ctx,w,h); const r=rimPosition(); drawHoop(ctx,r.x-r.r*.6,r.y-r.r*.4,r.r*1.95); drawPlayer(ctx,w*.18,h*.89,h*.38,m); drawAimPreview(ctx,w,h,m); drawTrails(ctx,w); if(m?.ball)drawBall(ctx,m.ball.x,m.ball.y,w*.018); drawGhostScore(ctx,w,h); }
  function drawBackground(ctx,w,h){ const court=state.skins.court; const sky=ctx.createLinearGradient(0,0,0,h*.7); sky.addColorStop(0,court==='night'?'#030713':court==='street'?'#111827':'#0a0c14'); sky.addColorStop(1,court==='beach'?'#3d2b18':'#1a1220'); ctx.fillStyle=sky; ctx.fillRect(0,0,w,h*.7); ctx.fillStyle='rgba(255,255,255,.04)'; for(let i=0;i<40;i++){ctx.beginPath();ctx.arc(i*w/40,h*.6+Math.sin(i)*4,5,0,Math.PI*2);ctx.fill();} const floor=ctx.createLinearGradient(0,h*.7,0,h); floor.addColorStop(0,court==='beach'?'#b77935':'#5a3018'); floor.addColorStop(1,court==='street'?'#1f2937':'#1a0c04'); ctx.fillStyle=floor; ctx.fillRect(0,h*.7,w,h*.3); ctx.strokeStyle='rgba(255,255,255,.18)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(w*.7,h*.95,w*.32,h*.18,0,Math.PI,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(w*.55,h*.83);ctx.lineTo(w*.85,h*.83);ctx.stroke(); }
  function drawHoop(ctx,cx,cy,scale){ const width=scale,board=state.skins.board; ctx.fillStyle=board==='cyber'?'#2563eb':board==='retro'?'#854d0e':'#3a2a1a'; ctx.fillRect(cx+width*.7,cy-width*.6,width*.18,width*4); ctx.fillStyle=board==='cyber'?'rgba(96,165,250,.92)':board==='retro'?'#f5deb3':'rgba(255,255,255,.92)'; ctx.strokeStyle='#1a0c04'; ctx.lineWidth=2; roundedRect(ctx,cx+width*.18,cy-width*.55,width*.7,width*1.4,4); ctx.fill();ctx.stroke(); const rimY=cy+width*.4,rimL=cx-width*.55,rimR=cx+width*.18; ctx.strokeStyle='#ff5d22';ctx.lineWidth=Math.max(3,width*.08);ctx.beginPath();ctx.moveTo(rimL,rimY);ctx.lineTo(rimR,rimY);ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.6)';ctx.lineWidth=1.2;for(let i=0;i<=9;i++){const tx=rimL+(rimR-rimL)*(i/9),bx=rimL+(rimR-rimL)*(.18+(i/9)*.66);ctx.beginPath();ctx.moveTo(tx,rimY);ctx.quadraticCurveTo((tx+bx)/2,rimY+width*.5,bx,rimY+width*.95);ctx.stroke();} }
  function drawPlayer(ctx,x,y,scale,m){ const phase=m?.charging?.valueOf()? .55 : m?.ball?.life<.25 ? .8 : 0, charge=m?.charging?m.power:0, h=scale, girl=profile.gender!=='boy'; ctx.save();ctx.translate(x,y);ctx.fillStyle='rgba(0,0,0,.45)';ctx.beginPath();ctx.ellipse(0,4,h*.16,h*.035,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d8a070';roundedRect(ctx,-h*.075,-h*.39,h*.05,h*.37,4);ctx.fill();roundedRect(ctx,h*.03,-h*.39,h*.05,h*.37,4);ctx.fill();ctx.fillStyle=girl?'#fb7185':'#ef6a1a';roundedRect(ctx,-h*.105,-h*.45+phase*h*.035,h*.21,h*.15,5);ctx.fill();ctx.save();ctx.translate(0,-h*.45+phase*h*.035);ctx.rotate(-phase*.12);ctx.fillStyle=girl?'#fff4f5':'#f4f1ea';roundedRect(ctx,-h*.105,-h*.31,h*.21,h*.31,6);ctx.fill();ctx.strokeStyle=girl?'#fb7185':'#ef6a1a';ctx.lineWidth=h*.015;ctx.stroke();ctx.fillStyle=girl?'#fb7185':'#ef6a1a';ctx.font=`800 ${h*.085}px monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(profile.number).slice(0,2),0,-h*.17);ctx.strokeStyle='#d8a070';ctx.lineWidth=h*.043;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-h*.08,-h*.26);ctx.lineTo(-h*.035-phase*h*.075,-h*.16-phase*h*.16);ctx.moveTo(h*.08,-h*.26);const arm=Math.PI*(-.3-phase*.8);ctx.lineTo(h*.08+Math.cos(arm)*h*.28,-h*.26+Math.sin(arm)*h*.28);ctx.stroke();ctx.fillStyle='#d8a070';ctx.beginPath();ctx.arc(0,-h*.4,h*.072,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1a0c04';ctx.beginPath();ctx.arc(0,-h*.42,h*.07,Math.PI,Math.PI*2);ctx.fill();if(girl){ctx.beginPath();ctx.ellipse(-h*.065,-h*.38,h*.035,h*.07,-.35,0,Math.PI*2);ctx.fill();}ctx.restore();ctx.fillStyle='rgba(255,255,255,.85)';ctx.font=`700 ${h*.045}px Inter Tight, sans-serif`;ctx.textAlign='center';ctx.fillText(profile.name,0,h*.08);if(charge>.05){const g=ctx.createRadialGradient(0,0,1,0,0,h*.22*charge);g.addColorStop(0,`rgba(255,176,102,${.55*charge})`);g.addColorStop(1,'rgba(255,176,102,0)');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(0,0,h*.22*charge,h*.055*charge,0,0,Math.PI*2);ctx.fill();}ctx.restore(); }
  function drawAimPreview(ctx,w,h,m){ if(!m||m.ball||m.ended)return;ctx.save();ctx.strokeStyle=`rgba(247,201,72,${.25+(m.power||0)*.5})`;ctx.lineWidth=2;ctx.setLineDash([4,6]);ctx.beginPath();const px=w*.18,py=h*.79-h*.22,ang=-Math.PI/2.4+(m.aimAngle*Math.PI/180),v=8+(m.power||.5)*12;let vx=Math.cos(ang)*v*60,vy=Math.sin(ang)*v*60,x=px,y=py;for(let i=0;i<60;i++){vy+=GRAVITY*.03;x+=vx*.03;y+=vy*.03;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);if(y>h*.92||x>w)break;}ctx.stroke();ctx.restore(); }
  function drawTrails(ctx,w){ game.trails.forEach(t=>{ const c={gold:'255,176,102',neon:'34,211,238',fire:'248,113,113',ice:'147,197,253'}[t.type]||'255,176,102';ctx.fillStyle=`rgba(${c},${t.life})`;ctx.beginPath();ctx.arc(t.x,t.y,w*.012,0,Math.PI*2);ctx.fill();t.life-=.02;});game.trails=game.trails.filter(t=>t.life>0); }
  function drawBall(ctx,x,y,r){ const skin=state.skins.ball, colors={classic:['#ffc185','#ef6a1a','#7a2c08'],neon:['#d9f99d','#22d3ee','#0e7490'],fire:['#fff7ad','#ef4444','#7f1d1d'],ice:['#eff6ff','#60a5fa','#1e3a8a'],gold:['#fff7ad','#facc15','#854d0e']}[skin]||['#ffc185','#ef6a1a','#7a2c08'];const g=ctx.createRadialGradient(x-r*.3,y-r*.3,r*.1,x,y,r);g.addColorStop(0,colors[0]);g.addColorStop(.55,colors[1]);g.addColorStop(1,colors[2]);ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#1a0c04';ctx.lineWidth=Math.max(1,r*.12);ctx.beginPath();ctx.moveTo(x-r,y);ctx.lineTo(x+r,y);ctx.moveTo(x,y-r);ctx.lineTo(x,y+r);ctx.stroke(); }
  function drawGhostScore(ctx,w,h){ const best=state.bestScore||0; if(!best)return; ctx.fillStyle='rgba(247,201,72,.18)';ctx.font=`800 ${Math.max(14,w*.02)}px JetBrains Mono, monospace`;ctx.textAlign='right';ctx.fillText(`GHOST BEST: ${best}`,w-18,28); }
  function roundedRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();}
  function loop(now){ if(!game.running)return; const raw=Math.min(.05,(now-game.last)/1000||.016),dt=game.slowMo>0?raw*.45:raw; game.last=now; if(game.slowMo>0)game.slowMo-=raw; update(dt); draw(); if(game.running)raf=requestAnimationFrame(loop); }
  function drawCover(){ const cv=$('#cover'); if(!cv)return; const ctx=cv.getContext('2d'); if(!ctx)return; const r=cv.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);cv.width=Math.max(1,Math.floor(r.width*d));cv.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0);const w=r.width,h=r.height;ctx.clearRect(0,0,w,h);drawBackground(ctx,w,h);drawHoop(ctx,w*.78,h*.42,w*.08);drawPlayer(ctx,w*.28,h*.74,h*.24,{charging:true,power:1});const t=(performance.now()/1500)%1;drawBall(ctx,w*.32+(w*.46)*t,(h*.72-h*.32)-Math.sin(t*Math.PI)*h*.22,h*.022);requestAnimationFrame(drawCover); }
  function bind(){ injectModeOptions(); const aim=$('#aim'); aim?.addEventListener('input',()=>{if(game.match)game.match.aimAngle=Number(aim.value||0);}); $('#aim-l')?.addEventListener('click',()=>{if(!aim)return;aim.value=String(Math.max(-45,Number(aim.value)-3));aim.dispatchEvent(new Event('input'));}); $('#aim-r')?.addEventListener('click',()=>{if(!aim)return;aim.value=String(Math.min(45,Number(aim.value)+3));aim.dispatchEvent(new Event('input'));}); const press=e=>{e.preventDefault();startShot();},release=e=>{e.preventDefault();releaseShot();}; $('#btn-shoot')?.addEventListener('pointerdown',press,{passive:false}); window.addEventListener('pointerup',release,{passive:false}); window.addEventListener('pointercancel',release,{passive:false}); document.addEventListener('keydown',e=>{if(e.repeat)return;if(e.code==='Space'){e.preventDefault();startShot();}if(e.key==='a'||e.key==='A'||e.key==='ArrowLeft')$('#aim-l')?.click();if(e.key==='d'||e.key==='D'||e.key==='ArrowRight')$('#aim-r')?.click();}); document.addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();releaseShot();}}); $('#btn-play')?.addEventListener('click',()=>{startMatch();$('#arena')?.scrollIntoView({behavior:'smooth',block:'start'});}); $('#ov-go')?.addEventListener('click',()=>startMatch()); $('#btn-end')?.addEventListener('click',()=>endMatch(true)); $('#ov-back')?.addEventListener('click',()=>endMatch(true)); $('#btn-hub')?.addEventListener('click',()=>{const hub=$('#hub');if(!hub)return;hub.hidden=false;hub.dataset.open='true';renderHub();}); $('#hub-close')?.addEventListener('click',()=>{const hub=$('#hub');if(!hub)return;hub.dataset.open='false';setTimeout(()=>hub.hidden=true,350);}); $$('.tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.tab').forEach(n=>n.classList.remove('active'));tab.classList.add('active');$$('.tab-panel').forEach(p=>p.classList.remove('active'));$(`.tab-panel[data-panel="${tab.dataset.tab}"]`)?.classList.add('active');})); $('#btn-tour')?.addEventListener('click',()=>{const hub=$('#hub');if(hub){hub.dataset.open='false';setTimeout(()=>hub.hidden=true,350);}state.tourIndex=0;startMatch(true);}); $('#btn-sound')?.addEventListener('click',e=>{soundOn=!soundOn;e.currentTarget.setAttribute('aria-pressed',soundOn?'true':'false');if(soundOn)tone('click');}); $('#btn-lang')?.addEventListener('click',()=>{lang=lang==='ro'?'en':'ro';localStorage.setItem('bvai.lang',lang);text('#lang-label',lang==='ro'?'EN':'RO');}); $('#btn-help')?.addEventListener('click',()=>$('#help')?.showModal()); $('#help-close')?.addEventListener('click',()=>$('#help')?.close()); $('#btn-reset')?.addEventListener('click',()=>{if(!confirm('Sigur ștergi progresul?'))return;localStorage.removeItem(STATE_KEY);state=readState();renderHero();renderHub();toast('OK','good');}); }
  function init(){ saveProfile(); ensureDaily(); ensureLeague(); syncLeagueName(); text('#lang-label',lang==='ro'?'EN':'RO'); text('#year',new Date().getFullYear()); setupCanvas(); bind(); renderHero(); renderHub(); text('#ov-title','Start'); text('#ov-msg','Țintește, ține apăsat pentru putere, eliberează lângă zona aurie.'); draw(); drawCover(); console.info('Basket vs AI Enhanced Pro loaded: pro-4'); }
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();